# -*- coding: utf-8 -*-
"""Robust Regression Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRxapUmB9Jf9r0Jp30nVWM64Vp-BuMYY

# **Part A: Conceptual Foundation (Theory)**
**Q1. What is Regularization in Machine Learning? Why is it needed?**

Answer:

Regularization is a technique used to reduce model complexity by adding a penalty term to the loss function. It helps prevent overfitting, improves model generalization, and makes predictions more stable on unseen data. Common regularization methods include Ridge (L2) and Lasso (L1).

**Q2. Difference between Ridge Regression (L2) and Lasso Regression (L1)**
Ridge Regression (L2)	Lasso Regression (L1)
Uses L2 penalty	Uses L1 penalty
Shrinks coefficients	Shrinks and removes coefficients
Keeps all features	Performs feature selection
Works well when all features are useful	Works well when many irrelevant features exist


**Q3. What is Cross Validation and why is it important?**

Answer:

Cross-validation is a model evaluation technique where the dataset is divided into multiple folds. The model is trained on some folds and tested on the remaining fold. This process repeats several times to provide a reliable estimate of model performance and reduce overfitting.

**Q4. Explain the following Cross Validation Techniques**

Answer:


a) K-Fold Cross Validation

The dataset is divided into K equal parts. The model trains on K−1 folds and tests on the remaining fold. This repeats K times.

b) Stratified K-Fold Cross Validation

Stratified K-Fold maintains the distribution of the target values across all folds. For regression, the target values are first grouped into bins before splitting.

c) Leave-One-Out Cross Validation (LOOCV)

Each observation acts once as the test set while the remaining observations form the training set. It provides almost unbiased performance estimates but is computationally expensive.

d) Time Series Split

Time Series Split is used for sequential data where future observations should never be used to predict past observations. It preserves chronological order.

**Q5. Why are tree-based models less sensitive to feature scaling?**

Answer:

Tree-based models split data based on feature thresholds rather than distances. Since scaling does not change the order of feature values, algorithms such as Decision Trees and Random Forests are generally unaffected by feature scaling.

# **Part B: Dataset Understanding & Preparation**
**Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

"""**Read Dataset**"""

df = pd.read_excel("Advanced_Regression_HousePrice_Dataset_3800.xlsx")

"""**Display Dataset**"""

df.head()

"""**Dataset Information**"""

df.info()

"""**Shape**"""

print("Rows and Columns :", df.shape)

"""**Missing Values**"""

df.isnull().sum()

"""**Duplicate Values**"""

df.duplicated().sum()

"""**Statistical Summary**"""

df.describe()

"""**Convert Date Column**"""

df['sale_date'] = pd.to_datetime(df['sale_date'])

"""**Create Time Features**"""

df['sale_year'] = df['sale_date'].dt.year
df['sale_month'] = df['sale_date'].dt.month

"""**Drop Property ID**"""

df.drop(['property_id','sale_date'],axis=1,inplace=True)

"""**Define Features and Target**"""

X = df.drop("house_price_inr",axis=1)
y = df["house_price_inr"]

"""**Train-Test Split**"""

X_train,X_test,y_train,y_test = train_test_split( X, y, test_size=0.20, random_state=42)

"""**Feature Scaling**"""

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""**Check Shapes**"""

print(X_train.shape)
print(X_test.shape)

"""**Correlation Heatmap**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))
plt.imshow(df.corr(numeric_only=True), cmap='coolwarm', aspect='auto')
plt.colorbar()
plt.xticks(range(len(df.select_dtypes(include=np.number).columns)),
           df.select_dtypes(include=np.number).columns,
           rotation=90)
plt.yticks(range(len(df.select_dtypes(include=np.number).columns)),
           df.select_dtypes(include=np.number).columns)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()

"""**House Price Distribution**"""

plt.figure(figsize=(8,5))
plt.hist(df['house_price_inr'], bins=30)
plt.title("House Price Distribution")
plt.xlabel("House Price")
plt.ylabel("Frequency")
plt.show()

"""**Scatter Plot**"""

plt.figure(figsize=(8,5))
plt.scatter(df['area_sqft'],df['house_price_inr'])
plt.xlabel("Area")
plt.ylabel("House Price")
plt.title("Area vs House Price")
plt.show()

"""# **Part C: Regularized Linear Models**
**Implement Ridge Regression (L2)**

**Import Required Libraries**
"""

from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

"""**Train Ridge Regression**"""

print("X_train:", X_train.shape)
print("X_train_scaled:", X_train_scaled.shape)
print("X_test:", X_test.shape)
print("X_test_scaled:", X_test_scaled.shape)
print("Model expects:", ridge.n_features_in_)

print(X_train.isnull().sum())

missing = X_train.isnull().sum()
print(missing[missing > 0])

"""**Predictions**"""

from sklearn.linear_model import Ridge

ridge = Ridge()

ridge.fit(X_train_scaled, y_train)

ridge_train_pred = ridge.predict(X_train_scaled)
ridge_test_pred = ridge.predict(X_test_scaled)

ridge = Ridge()

ridge.fit(X_train, y_train)

ridge_train_pred = ridge.predict(X_train)
ridge_test_pred = ridge.predict(X_test)

"""**Ridge Performance**"""

ridge_train_r2 = r2_score(y_train, ridge_train_pred)
ridge_test_r2 = r2_score(y_test, ridge_test_pred)

ridge_train_mae = mean_absolute_error(y_train, ridge_train_pred)
ridge_test_mae = mean_absolute_error(y_test, ridge_test_pred)

ridge_train_rmse = np.sqrt(mean_squared_error(y_train, ridge_train_pred))
ridge_test_rmse = np.sqrt(mean_squared_error(y_test, ridge_test_pred))

print("Training R² :", ridge_train_r2)
print("Testing R² :", ridge_test_r2)

print("Training MAE :", ridge_train_mae)
print("Testing MAE :", ridge_test_mae)

print("Training RMSE :", ridge_train_rmse)
print("Testing RMSE :", ridge_test_rmse)

"""**Train Lasso**"""

lasso = Lasso()

lasso.fit(X_train_scaled, y_train)

"""**Prediction**"""

lasso_train_pred = lasso.predict(X_train_scaled)
lasso_test_pred = lasso.predict(X_test_scaled)

"""**Lasso Performance**"""

lasso_train_r2 = r2_score(y_train, lasso_train_pred)
lasso_test_r2 = r2_score(y_test, lasso_test_pred)

lasso_train_mae = mean_absolute_error(y_train, lasso_train_pred)
lasso_test_mae = mean_absolute_error(y_test, lasso_test_pred)

lasso_train_rmse = np.sqrt(mean_squared_error(y_train, lasso_train_pred))
lasso_test_rmse = np.sqrt(mean_squared_error(y_test, lasso_test_pred))

print("Training R² :", lasso_train_r2)
print("Testing R² :", lasso_test_r2)

print("Training MAE :", lasso_train_mae)
print("Testing MAE :", lasso_test_mae)

print("Training RMSE :", lasso_train_rmse)
print("Testing RMSE :", lasso_test_rmse)

"""**Ridge Grid Search**"""

ridge_params = {
    'alpha':[0.01,0.1,1,10,50,100]
}

ridge_grid = GridSearchCV(
    Ridge(),
    ridge_params,
    cv=5,
    scoring='r2'
)

ridge_grid.fit(X_train_scaled,y_train)

print("Best Alpha :", ridge_grid.best_params_)
print("Best Score :", ridge_grid.best_score_)

"""**Best Ridge Model**"""

best_ridge = ridge_grid.best_estimator_

ridge_pred = best_ridge.predict(X_test_scaled)

print("R² Score :", r2_score(y_test,ridge_pred))

"""**Lasso Grid Search**"""

lasso_params = {
    'alpha':[0.0001,0.001,0.01,0.1,1,10]
}

lasso_grid = GridSearchCV(
    Lasso(max_iter=10000),
    lasso_params,
    cv=5,
    scoring='r2'
)

lasso_grid.fit(X_train_scaled,y_train)

print("Best Alpha :", lasso_grid.best_params_)
print("Best Score :", lasso_grid.best_score_)

"""**Best Lasso Model**"""

best_lasso = lasso_grid.best_estimator_

lasso_pred = best_lasso.predict(X_test_scaled)

print("R² Score :", r2_score(y_test,lasso_pred))

"""**Performance Table**"""

comparison = pd.DataFrame({

'Model':['Ridge','Lasso'],

'Train R²':[ridge_train_r2,lasso_train_r2],

'Test R²':[ridge_test_r2,lasso_test_r2],

'Train RMSE':[ridge_train_rmse,lasso_train_rmse],

'Test RMSE':[ridge_test_rmse,lasso_test_rmse]

})

comparison

"""**Coefficient Comparison**"""

coef = pd.DataFrame({

'Feature':X.columns,

'Ridge':best_ridge.coef_,

'Lasso':best_lasso.coef_

})

coef

"""**Coefficient Comparison**"""

plt.figure(figsize=(12,6))

plt.plot(coef['Feature'],coef['Ridge'],label='Ridge',marker='o')

plt.plot(coef['Feature'],coef['Lasso'],label='Lasso',marker='x')

plt.xticks(rotation=90)

plt.legend()

plt.title("Ridge vs Lasso Coefficients")

plt.tight_layout()

plt.show()

"""**Actual vs Predicted (Ridge)**"""

plt.figure(figsize=(6,6))

plt.scatter(y_test,ridge_pred)

plt.xlabel("Actual")

plt.ylabel("Predicted")

plt.title("Ridge Regression")

plt.show()

"""**Actual vs Predicted (Lasso)**"""

plt.figure(figsize=(6,6))

plt.scatter(y_test,lasso_pred)

plt.xlabel("Actual")

plt.ylabel("Predicted")

plt.title("Lasso Regression")

plt.show()

"""Residual Plot (Ridge)"""

residual = y_test-ridge_pred

plt.figure(figsize=(6,5))

plt.scatter(ridge_pred,residual)

plt.axhline(y=0,color='red')

plt.xlabel("Predicted")

plt.ylabel("Residual")

plt.title("Residual Plot")

plt.show()

"""# **Part D: Cross Validation Techniques**

**Import Libraries**
"""

from sklearn.model_selection import (KFold, StratifiedKFold, LeaveOneOut, TimeSeriesSplit, cross_val_score)

"""**K-Fold Cross Validation**"""

ridge_cv = Ridge(alpha=ridge_grid.best_params_['alpha'])

kfold = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

kfold_scores = cross_val_score(
    ridge_cv,
    X_train_scaled,
    y_train,
    cv=kfold,
    scoring='r2'
)

print("K-Fold Scores")
print(kfold_scores)

print("Average Score :", np.mean(kfold_scores))

"""**Stratified K-Fold Cross Validation**"""

y_bins = pd.qcut(y_train, q=5, labels=False)

"""**Perform Stratified K-Fold**"""

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = []

for train_index, test_index in skf.split(X_train_scaled, y_bins):

    X_tr = X_train_scaled[train_index]
    X_te = X_train_scaled[test_index]

    y_tr = y_train.iloc[train_index]
    y_te = y_train.iloc[test_index]

    model = Ridge(alpha=ridge_grid.best_params_['alpha'])

    model.fit(X_tr, y_tr)

    pred = model.predict(X_te)

    scores.append(r2_score(y_te, pred))

print("Stratified K-Fold Scores")
print(scores)

print("Average :", np.mean(scores))

"""**Leave-One-Out Cross Validation (LOOCV)**"""

loo = LeaveOneOut()

X_small = X_train_scaled[:300]
y_small = y_train.iloc[:300]

loo_scores = cross_val_score(
    Ridge(alpha=ridge_grid.best_params_['alpha']),
    X_small,
    y_small,
    cv=loo,
    scoring='r2'
)

print("LOOCV Mean Score :", np.mean(loo_scores))

"""**Time Series Split**"""

tscv = TimeSeriesSplit(n_splits=5)

time_scores = []

for train_index, test_index in tscv.split(X_train_scaled):

    X_tr = X_train_scaled[train_index]
    X_te = X_train_scaled[test_index]

    y_tr = y_train.iloc[train_index]
    y_te = y_train.iloc[test_index]

    model = Ridge(alpha=ridge_grid.best_params_['alpha'])

    model.fit(X_tr, y_tr)

    pred = model.predict(X_te)

    score = r2_score(y_te, pred)

    time_scores.append(score)

print("Time Series Scores")
print(time_scores)

print("Average :", np.mean(time_scores))

"""**Compare Cross Validation Techniques**"""

cv_results = pd.DataFrame({

'Method':[
    'KFold',
    'Stratified KFold',
    'Leave One Out',
    'Time Series'
],

'Average R2':[
    np.mean(kfold_scores),
    np.mean(scores),
    np.mean(loo_scores),
    np.mean(time_scores)
]

})

cv_results

"""**Plot Comparison**"""

plt.figure(figsize=(8,5))

plt.bar(
    cv_results['Method'],
    cv_results['Average R2']
)

plt.title("Cross Validation Comparison")

plt.xlabel("Method")

plt.ylabel("Average R² Score")

plt.xticks(rotation=15)

plt.show()

"""# **PART E: Tree-Based Models**

**Import Libraries**
"""

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

"""**Decision Tree Regressor**"""

dt = DecisionTreeRegressor(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

"""**Decision Tree Performance**"""

dt_mae = mean_absolute_error(y_test, dt_pred)
dt_mse = mean_squared_error(y_test, dt_pred)
dt_rmse = np.sqrt(dt_mse)
dt_r2 = r2_score(y_test, dt_pred)

print("Decision Tree Results")
print("MAE :", dt_mae)
print("MSE :", dt_mse)
print("RMSE :", dt_rmse)
print("R2 Score :", dt_r2)

"""**Hyperparameter Tuning**"""

from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth':[5,10,15,None],
    'min_samples_split':[2,5,10],
    'min_samples_leaf':[1,2,4]
}

grid_dt = GridSearchCV(
    DecisionTreeRegressor(random_state=42),
    param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1
)

grid_dt.fit(X_train,y_train)

print("Best Parameters")
print(grid_dt.best_params_)

best_dt = grid_dt.best_estimator_

"""**Best Decision Tree**"""

best_dt_pred = best_dt.predict(X_test)

print("R2 :",r2_score(y_test,best_dt_pred))
print("RMSE :",np.sqrt(mean_squared_error(y_test,best_dt_pred)))

"""**Random Forest**"""

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train,y_train)

rf_pred = rf.predict(X_test)

"""**Random Forest Performance**"""

rf_mae = mean_absolute_error(y_test,rf_pred)
rf_mse = mean_squared_error(y_test,rf_pred)
rf_rmse = np.sqrt(rf_mse)
rf_r2 = r2_score(y_test,rf_pred)

print("Random Forest Results")

print("MAE :",rf_mae)
print("MSE :",rf_mse)
print("RMSE :",rf_rmse)
print("R2 :",rf_r2)

"""**Feature Importance**"""

importance = pd.DataFrame({
    'Feature':X.columns,
    'Importance':rf.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

importance

"""**Feature Importance Graph**"""

plt.figure(figsize=(10,6))

plt.barh(
    importance['Feature'],
    importance['Importance']
)

plt.title("Random Forest Feature Importance")

plt.xlabel("Importance")

plt.gca().invert_yaxis()

plt.show()

"""## **PART F: Support Vector Regression**"""

from sklearn.svm import SVR

"""**Linear Kernel**"""

svr_linear = SVR(kernel='linear')

svr_linear.fit(X_train_scaled,y_train)

linear_pred = svr_linear.predict(X_test_scaled)

"""**RBF Kernel**"""

svr_rbf = SVR(
    kernel='rbf',
    C=100,
    gamma='scale'
)

svr_rbf.fit(X_train_scaled,y_train)

rbf_pred = svr_rbf.predict(X_test_scaled)

"""**Performance**"""

print("Linear Kernel")

print("MAE :",mean_absolute_error(y_test,linear_pred))

print("RMSE :",np.sqrt(mean_squared_error(y_test,linear_pred)))

print("R2 :",r2_score(y_test,linear_pred))


print("\nRBF Kernel")

print("MAE :",mean_absolute_error(y_test,rbf_pred))

print("RMSE :",np.sqrt(mean_squared_error(y_test,rbf_pred)))

print("R2 :",r2_score(y_test,rbf_pred))

"""**Hyperparameter Tuning**"""

params = {

'C':[1,10,100],

'gamma':['scale',0.1,0.01],

'kernel':['rbf']

}

grid_svr = GridSearchCV(
    SVR(),
    params,
    cv=5,
    scoring='r2',
    n_jobs=-1
)

grid_svr.fit(
    X_train_scaled,
    y_train
)

print(grid_svr.best_params_)

best_svr = grid_svr.best_estimator_

"""**Best SVR**"""

best_pred = best_svr.predict(X_test_scaled)

print("Best SVR")

print("R2 :",r2_score(y_test,best_pred))

print("RMSE :",np.sqrt(mean_squared_error(y_test,best_pred)))

"""# **PART G: Model Comparison**"""

results = pd.DataFrame({

'Model':[
'Ridge',
'Lasso',
'Decision Tree',
'Random Forest',
'SVR'
],

'MAE':[
mean_absolute_error(y_test,ridge_pred),
mean_absolute_error(y_test,lasso_pred),
dt_mae,
rf_mae,
mean_absolute_error(y_test,best_pred)
],

'RMSE':[
np.sqrt(mean_squared_error(y_test,ridge_pred)),
np.sqrt(mean_squared_error(y_test,lasso_pred)),
dt_rmse,
rf_rmse,
np.sqrt(mean_squared_error(y_test,best_pred))
],

'R2 Score':[
r2_score(y_test,ridge_pred),
r2_score(y_test,lasso_pred),
dt_r2,
rf_r2,
r2_score(y_test,best_pred)
]

})

results

"""**Best Model**"""

best_model = results.loc[
results['R2 Score'].idxmax()
]

print(best_model)

"""Comparison Graph"""

plt.figure(figsize=(10,5))

plt.bar(
results['Model'],
results['R2 Score']
)

plt.title("Model Comparison")

plt.ylabel("R2 Score")

plt.show()

"""**Actual vs Predicted**"""

plt.figure(figsize=(6,6))

plt.scatter(
y_test,
rf_pred
)

plt.xlabel("Actual")

plt.ylabel("Predicted")

plt.title("Actual vs Predicted (Random Forest)")

plt.show()

"""**Residual Plot**"""

residual = y_test-rf_pred

plt.figure(figsize=(6,5))

plt.scatter(
rf_pred,
residual
)

plt.axhline(0,color='red')

plt.xlabel("Predicted")

plt.ylabel("Residual")

plt.title("Residual Plot")

plt.show()

"""# **PART H: Final Report**

**Objective**

The objective of this project was to develop robust regression models for predicting house prices while reducing overfitting through regularization and advanced machine learning algorithms.

**Models Used**
Ridge Regression
Lasso Regression
Decision Tree Regressor
Random Forest Regressor
Support Vector Regression
Evaluation Metrics
Mean Absolute Error (MAE)
Mean Squared Error (MSE)
Root Mean Squared Error (RMSE)
R² Score


**Findings**
Ridge Regression effectively reduced coefficient magnitudes using L2 regularization.
Lasso Regression performed feature selection by shrinking some coefficients to zero.
Decision Tree captured nonlinear relationships but may overfit without tuning.
Random Forest reduced overfitting by averaging multiple decision trees and generally achieved the best predictive performance.
Support Vector Regression modeled complex relationships, though performance depended on kernel choice and hyperparameter tuning.



**Conclusion**

Among all the implemented models, the one with the highest R² score and lowest RMSE should be selected as the best-performing model based on your results. In many house-price prediction tasks, Random Forest Regressor often performs the best because it captures nonlinear relationships while reducing overfitting through ensemble learning.
"""